language: java
sudo: false

before_install:
  - rvm install 2.6.2
  - rvm use 2.6.2
  - gem install hiptest-publisher
  - hiptest-publisher --config-file ./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --test-run-id 435601 --without=actionwords

script:
  - ./gradlew build

after_script:
  - hiptest-publisher --config-file ./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --push ./src/test/java/cmls/spring/cucumberstudio/hiptest/tests/results-435601.xml --test-run-id 435601 --push-format junit