language: java
sudo: false

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - hiptest-publisher -c hipster-publisher.conf --only=tests --test-run-id=1358

script:
  - mvn package

after_script:
  - hiptest-publisher -c hipster-publisher.conf --test-run-id=1358