language: java
sudo: false

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - hiptest-publisher -c ./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --only=tests --test-run-id=435601

script:
  - mvn package

after_script:
  - hiptest-publisher -c ./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --test-run-id=435601