language: java
sudo: false

before_install:
  - rvm install 2.6.2
  - rvm use 2.6.2
  - gem install hiptest-publisher
  - hiptest-publisher -c ./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --test-run-id 435601 --without=actionwords --force

script:
  - ./gradlew build

after_script:
  - hiptest-publisher --config=./src/test/java/cmls/spring/cucumberstudio/hiptest/hiptest-publisher.conf --test-run-id=435601 --without=actionwords --push-format=junit